plugins {
    id 'com.android.application'
}

def apikeyPropertiesFile = rootProject.file("apikey.properties")
def apikeyProperties = new Properties()
apikeyProperties.load(new FileInputStream(apikeyPropertiesFile))

android {
    compileSdkVersion 'android-36.1'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion 26
        targetSdk 36
        vectorDrawables.useSupportLibrary = true

        missingDimensionStrategy 'device', 'anyDevice'
        applicationId "no.jkvatne.android.motimeekthandler"
        versionCode 1
        versionName "1.0"
        buildConfigField("String", "SERVER_URL", apikeyProperties['SERVER_URL'])
    }

    buildTypes {
        release {
            minifyEnabled true
        }
    }
    namespace 'no.jkvatne.android.motimeekthandler'
    buildFeatures {
        buildConfig true
    }
    buildToolsVersion '36.0.0'
    ndkVersion '25.2.9519653'

    packaging {
        resources {
            // Option 1: Pick the first occurrence found
            pickFirsts += "META-INF/NOTICE.md"
            pickFirsts += "META-INF/LICENSE.md"
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.databinding:databinding-compiler:9.2.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'androidx.core:core:1.18.0'
    implementation 'com.github.mik3y:usb-serial-for-android:3.10.0'
}
